[websubhub.config.server]
port = 9190
serverId = "hub-1"

# [websubhub.config.server.auth]
# scopeKey = "scope"
# issuer = "https://localhost:9443/oauth2/token"
# audience = "ballerina"
# jwksUrl = "https://localhost:9443/oauth2/jwks"
# trustStore = "./resources/client-truststore.jks"
# trustStorePassword = "wso2carbon"

[websubhub.config.state.snapshot]
url = "http://localhost:10001"

[websubhub.config.state.events]
topic = "websub-events"
consumerGroup = "websub-events-consumer"

[websubhub.config.kafka.connection]
bootstrapServers = "localhost:29092"

[websubhub.config.kafka.consumer]
maxPollRecords = 50
pollingInterval = 10.0
gracefulClosePeriod = 5.0

[websubhub.config.delivery]
timeout = 60.0

[websubhub.config.delivery.retry]
count = 3
interval = 3.0
statusCodes = [500, 502, 503]

[ballerina.log]
level = "DEBUG"
