[websubhub.config]
# Flag to check whether to enable/disable security
securityOn = true

# Server ID is is used to uniquely identify each server 
# Each server must have a unique ID
serverId = "hub-1"

# IP and Port of the Kafka bootstrap node
kafkaBootstrapNode = "localhost:9094"

# Maximum number of records returned in a single call to consumer-poll
kafkaConsumerMaxPollRecords = 50

# Kafka topic which is stores websub-events for this server
websubEventsTopic = "websub-events"

# Consolidator HTTP endpoint to be used to retrieve current state-snapshot
stateSnapshotEndpoint = "http://localhost:10001"

# The interval in which Kafka consumers wait for new messages
pollingInterval = 10.0

# The period in which Kafka close method waits to complete
gracefulClosePeriod = 5.0

# The port that is used to start the hub
hubPort = 9000

# SSL keystore file path
sslKeystorePath = "./resources/hub.keystore.jks"

# SSL keystore password
sslKeystorePassword = "password"

# The period between retry requests
messageDeliveryRetryInterval = 3.0

# The maximum retry count
messageDeliveryCount = 3

# The message delivery timeout
messageDeliveryTimeout = 10.0

# The HTTP status codes for which the client should retry
messageDeliveryRetryableStatusCodes = [500, 502, 503]

# The Oauth2 authorization related configurations
[websubhub.config.oauth2Config]
issuer = "https://localhost:9443/oauth2/token"
audience = "ballerina"
jwksUrl = "https://localhost:9443/oauth2/jwks"
trustStore = "conf/resources/client-truststore.jks"
trustStorePassword = "wso2carbon"

# The MTLS configurations related to Kafka connection
[websubhub.config.kafkaMtlsConfig]
cert.path = "conf/resources/brokercerts/client-truststore.jks"
cert.password = "password"
key.keyStore.path = "conf/resources/brokercerts/client-keystore.jks"
key.keyStore.password = "password"

[ballerina.log]
level = "DEBUG"
