[consolidator.config]
# IP and Port of the Kafka bootstrap node
kafkaBootstrapNode = "localhost:9094"

# Kafka topic which stores websub-events for this server
websubEventsTopic = "websub-events"

# Kafka topic which stores the current snapshot for the websub-events
websubEventsSnapshotTopic = "websub-events-snapshot"

# The interval in which Kafka consumers wait for new messages
pollingInterval = 10.0

# The period in which Kafka close method waits to complete
gracefulClosePeriod = 5.0

# The port that is used to start the HTTP endpoint for consolidator
consolidatorHttpEndpointPort = 10001

# The MTLS configurations related to Kafka connection
[consolidator.config.kafkaMtlsConfig]
cert.path = "./resources/brokercerts/client-truststore.jks"
cert.password = "password"
key.keyStore.path = "./resources/brokercerts/client-keystore.jks"
key.keyStore.password = "password"
