[websubhub.config.server]
port = 9000
id = "hub-1"

[websubhub.config.server.secureSocket]
key.path = "conf/resources/hub.keystore.jks"
key.password = "password"

[websubhub.config.state.snapshot]
url = "http://localhost:10001"

[websubhub.config.state.events]
topic = "websub-events"
consumerGroup = "websub-events-consumer"

[websubhub.config.kafka.connection]
bootstrapServers = "localhost:9092"

[websubhub.config.kafka.consumer]
maxPollRecords = 50
pollingInterval = 10.0
gracefulClosePeriod = 5.0

[websubhub.config.delivery]
timeout = 60.0

[websubhub.config.delivery.retry]
count = 3
interval = 3.0
backOffFactor = 2.0
maxWaitInterval = 20.0
statusCodes = [500, 502, 503]
