[websubhub.consolidator.config.server]
port = 10001

[websubhub.consolidator.config.state.snapshot]
topic = "websub-events-snapshot"
consumerGroup = "websub-events-snapshot-consumer"

[websubhub.consolidator.config.state.events]
topic = "websub-events"
consumerGroup = "consolidator-websub-events-consumer"

[websubhub.consolidator.config.kafka.connection]
bootstrapServers = "localhost:9092"

[websubhub.consolidator.config.kafka.consumer]
maxPollRecords = 50
pollingInterval = 10.0
gracefulClosePeriod = 5.0
