name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04
    
    if: github.repository_owner == 'wso2'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaDistributionVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
          if [ -z "$BAL_VERSION" ]; then
            BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"
      
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ env.BAL_VERSION }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      
      - name: Build the Package
        run: |
          ./gradlew clean build
      
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: components/**/target/bin

  trivy-scan:
    name: Trivy Vulnerability Scan
    needs: build
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        scan-path:
          - "components/websubhub/target/bin"
          - "components/websubhub-consolidator/target/bin"
    steps:
      - name: Download build output
        uses: actions/download-artifact@v5
        with:
          name: build-output
          path: components
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
        with:
          scan-type: "rootfs"
          scan-ref: ${{ matrix.scan-path }}
          format: "table"
          timeout: "10m0s"
          exit-code: "1"
          scanners: "vuln"
          cache-dir: "/tmp/trivy-cache"
